language: java
sudo: false
jdk:
  - openjdk8
before_script:
  - ulimit -n 4096
before_install:
  - echo "MAVEN_OPTS='-Xms2g -Xmx3g'" > ~/.mavenrc
script:
  - travis_wait 30 mvn test -B -V -Djava.util.logging.config.file=logging.properties
