sudo: false
language:
    - java
install:
  - mvn --version
script: 
  - mvn -T4 -pl quickfixj-codegenerator install
  - mvn -T4 -pl quickfixj-dictgenerator install
  - mvn -T4 -pl quickfixj-core install -DskipTests=true -Dmaven.javadoc.skip=true
jdk:
  - oraclejdk8
env:
  - MAVEN_OPTS="-Xms2048m -Xmx=2048m"
branches:
  only:
    - travis-ci-build

