blank_issues_enabled: false
contact_links:
  - name: QuickFIX/J mailing list
    url: https://sourceforge.net/projects/quickfixj/lists/quickfixj-users
    about: Please ask usage related questions here.
  - name:  Stack Overflow
    url: https://stackoverflow.com/questions/ask?tags=quickfixj
    about: Please ask usage releated questions here and tag your question with "quickfixj".
  - name: Discussions
    url: https://github.com/quickfix-j/quickfixj/discussions
    about: Please ask usage related questions here.
